# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\mainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
	def setupUi(self, MainWindow):
		MainWindow.setObjectName("MainWindow")
		MainWindow.resize(769, 595)
		MainWindow.setStyleSheet("QFrame {\n"
"    color: rgb(40, 40, 40)\n"
"}")
		self.centralwidget = QtWidgets.QWidget(MainWindow)
		self.centralwidget.setObjectName("centralwidget")
		self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
		self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
		self.verticalLayout_2.setSpacing(0)
		self.verticalLayout_2.setObjectName("verticalLayout_2")
		self.frame = QtWidgets.QFrame(self.centralwidget)
		self.frame.setStyleSheet("background-color: rgb(40, 40, 40);")
		self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
		self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
		self.frame.setObjectName("frame")
		self.gridLayout = QtWidgets.QGridLayout(self.frame)
		self.gridLayout.setObjectName("gridLayout")
		self.lineEditCpfIn = QtWidgets.QLineEdit(self.frame)
		sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
		sizePolicy.setHorizontalStretch(0)
		sizePolicy.setVerticalStretch(0)
		sizePolicy.setHeightForWidth(self.lineEditCpfIn.sizePolicy().hasHeightForWidth())
		self.lineEditCpfIn.setSizePolicy(sizePolicy)
		self.lineEditCpfIn.setMinimumSize(QtCore.QSize(550, 40))
		self.lineEditCpfIn.setStyleSheet("QLineEdit {\n"
"    border: 2px solid rgb(45, 45, 45);\n"
"    border-radius: 5px;\n"
"    padding: 10px;\n"
"    background-color: rgb(30, 30, 30);\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"QLineEdit:hover {\n"
"    border: 2px solid rgb(55, 55, 55);\n"
"}\n"
"\n"
"QLineEdit:focus {\n"
"    border: 2px solid rgb(94, 53, 177);\n"
"}")
		self.lineEditCpfIn.setMaxLength(60)
		self.lineEditCpfIn.setObjectName("lineEditCpfIn")
		self.gridLayout.addWidget(self.lineEditCpfIn, 3, 0, 1, 1)
		self.lineEditNascimentoIn = QtWidgets.QLineEdit(self.frame)
		sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
		sizePolicy.setHorizontalStretch(0)
		sizePolicy.setVerticalStretch(0)
		sizePolicy.setHeightForWidth(self.lineEditNascimentoIn.sizePolicy().hasHeightForWidth())
		self.lineEditNascimentoIn.setSizePolicy(sizePolicy)
		self.lineEditNascimentoIn.setMinimumSize(QtCore.QSize(550, 40))
		self.lineEditNascimentoIn.setStyleSheet("QLineEdit {\n"
"    border: 2px solid rgb(45, 45, 45);\n"
"    border-radius: 5px;\n"
"    padding: 10px;\n"
"    background-color: rgb(30, 30, 30);\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"QLineEdit:hover {\n"
"    border: 2px solid rgb(55, 55, 55);\n"
"}\n"
"\n"
"QLineEdit:focus {\n"
"    border: 2px solid rgb(94, 53, 177);\n"
"}")
		self.lineEditNascimentoIn.setMaxLength(60)
		self.lineEditNascimentoIn.setObjectName("lineEditNascimentoIn")
		self.gridLayout.addWidget(self.lineEditNascimentoIn, 4, 0, 1, 1)
		self.horizontalLayout = QtWidgets.QHBoxLayout()
		self.horizontalLayout.setObjectName("horizontalLayout")
		self.lineEditCpfBusca = QtWidgets.QLineEdit(self.frame)
		sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
		sizePolicy.setHorizontalStretch(0)
		sizePolicy.setVerticalStretch(0)
		sizePolicy.setHeightForWidth(self.lineEditCpfBusca.sizePolicy().hasHeightForWidth())
		self.lineEditCpfBusca.setSizePolicy(sizePolicy)
		self.lineEditCpfBusca.setMinimumSize(QtCore.QSize(300, 40))
		self.lineEditCpfBusca.setStyleSheet("QLineEdit {\n"
"    border: 2px solid rgb(45, 45, 45);\n"
"    border-radius: 5px;\n"
"    padding: 10px;\n"
"    background-color: rgb(30, 30, 30);\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"QLineEdit:hover {\n"
"    border: 2px solid rgb(55, 55, 55);\n"
"}\n"
"\n"
"QLineEdit:focus {\n"
"    border: 2px solid  rgb(94, 53, 177)\n"
"}")
		self.lineEditCpfBusca.setMaxLength(60)
		self.lineEditCpfBusca.setObjectName("lineEditCpfBusca")
		self.horizontalLayout.addWidget(self.lineEditCpfBusca)
		self.pushButtonBuscar = QtWidgets.QPushButton(self.frame)
		self.pushButtonBuscar.setMinimumSize(QtCore.QSize(100, 30))
		self.pushButtonBuscar.setMaximumSize(QtCore.QSize(100, 40))
		font = QtGui.QFont()
		font.setFamily("Unispace")
		font.setBold(True)
		font.setWeight(75)
		self.pushButtonBuscar.setFont(font)
		self.pushButtonBuscar.setStyleSheet("QPushButton {\n"
"    \n"
"    background-color: rgb(94, 53, 177);\n"
"    border: 2px solid rgb(81, 45, 168);\n"
"    border-radius: 5px;\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    \n"
"    background-color: rgb(60, 60, 60);\n"
"    border: 2px solid rgb(70,70,70);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    \n"
"    background-color: rgb(40, 40, 40);\n"
"    border: 2px solid rgb(81, 45, 168);\n"
"    color: rgb(255, 255, 255);\n"
"}")
		self.pushButtonBuscar.setObjectName("pushButtonBuscar")
		self.horizontalLayout.addWidget(self.pushButtonBuscar)
		self.gridLayout.addLayout(self.horizontalLayout, 9, 0, 1, 1)
		self.lineEditNomeIn = QtWidgets.QLineEdit(self.frame)
		self.lineEditNomeIn.setEnabled(True)
		sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
		sizePolicy.setHorizontalStretch(0)
		sizePolicy.setVerticalStretch(0)
		sizePolicy.setHeightForWidth(self.lineEditNomeIn.sizePolicy().hasHeightForWidth())
		self.lineEditNomeIn.setSizePolicy(sizePolicy)
		self.lineEditNomeIn.setMinimumSize(QtCore.QSize(550, 40))
		self.lineEditNomeIn.setStyleSheet("QLineEdit {\n"
"    border: 2px solid rgb(45, 45, 45);\n"
"    border-radius: 5px;\n"
"    padding: 10px;\n"
"    background-color: rgb(30, 30, 30);\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"QLineEdit:hover {\n"
"    border: 2px solid rgb(55, 55, 55);\n"
"}\n"
"\n"
"QLineEdit:focus {\n"
"    border: 2px solid rgb(94, 53, 177);\n"
"}")
		self.lineEditNomeIn.setMaxLength(60)
		self.lineEditNomeIn.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
		self.lineEditNomeIn.setObjectName("lineEditNomeIn")
		self.gridLayout.addWidget(self.lineEditNomeIn, 1, 0, 1, 1)
		self.lineEditNascimentoOut = QtWidgets.QLineEdit(self.frame)
		self.lineEditNascimentoOut.setEnabled(False)
		sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
		sizePolicy.setHorizontalStretch(0)
		sizePolicy.setVerticalStretch(0)
		sizePolicy.setHeightForWidth(self.lineEditNascimentoOut.sizePolicy().hasHeightForWidth())
		self.lineEditNascimentoOut.setSizePolicy(sizePolicy)
		self.lineEditNascimentoOut.setMinimumSize(QtCore.QSize(550, 40))
		self.lineEditNascimentoOut.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
		self.lineEditNascimentoOut.setStyleSheet("QLineEdit {\n"
"    border: 2px solid rgb(45, 45, 45);\n"
"    border-radius: 5px;\n"
"    padding: 10px;\n"
"    background-color: rgb(30, 30, 30);\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"QLineEdit:hover {\n"
"    border: 2px solid rgb(55, 55, 55);\n"
"}\n"
"\n"
"QLineEdit:focus {\n"
"    border: 2px solid rgb(53, 97, 255);\n"
"}")
		self.lineEditNascimentoOut.setMaxLength(60)
		self.lineEditNascimentoOut.setObjectName("lineEditNascimentoOut")
		self.gridLayout.addWidget(self.lineEditNascimentoOut, 15, 0, 1, 1)
		self.lineEditNomeOut = QtWidgets.QLineEdit(self.frame)
		self.lineEditNomeOut.setEnabled(False)
		sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
		sizePolicy.setHorizontalStretch(0)
		sizePolicy.setVerticalStretch(0)
		sizePolicy.setHeightForWidth(self.lineEditNomeOut.sizePolicy().hasHeightForWidth())
		self.lineEditNomeOut.setSizePolicy(sizePolicy)
		self.lineEditNomeOut.setMinimumSize(QtCore.QSize(550, 40))
		self.lineEditNomeOut.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
		self.lineEditNomeOut.setStyleSheet("QLineEdit {\n"
"    border: 2px solid rgb(45, 45, 45);\n"
"    border-radius: 5px;\n"
"    padding: 10px;\n"
"    background-color: rgb(30, 30, 30);\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"QLineEdit:hover {\n"
"    border: 2px solid rgb(55, 55, 55);\n"
"}\n"
"\n"
"QLineEdit:focus {\n"
"    border: 2px solid rgb(53, 97, 255);\n"
"}")
		self.lineEditNomeOut.setMaxLength(60)
		self.lineEditNomeOut.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
		self.lineEditNomeOut.setObjectName("lineEditNomeOut")
		self.gridLayout.addWidget(self.lineEditNomeOut, 13, 0, 1, 1)
		self.lineEditCidadeIn = QtWidgets.QLineEdit(self.frame)
		sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
		sizePolicy.setHorizontalStretch(0)
		sizePolicy.setVerticalStretch(0)
		sizePolicy.setHeightForWidth(self.lineEditCidadeIn.sizePolicy().hasHeightForWidth())
		self.lineEditCidadeIn.setSizePolicy(sizePolicy)
		self.lineEditCidadeIn.setMinimumSize(QtCore.QSize(550, 40))
		self.lineEditCidadeIn.setStyleSheet("QLineEdit {\n"
"    border: 2px solid rgb(45, 45, 45);\n"
"    border-radius: 5px;\n"
"    padding: 10px;\n"
"    background-color: rgb(30, 30, 30);\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"QLineEdit:hover {\n"
"    border: 2px solid rgb(55, 55, 55);\n"
"}\n"
"\n"
"QLineEdit:focus {\n"
"    border: 2px solid rgb(94, 53, 177);\n"
"}")
		self.lineEditCidadeIn.setMaxLength(60)
		self.lineEditCidadeIn.setObjectName("lineEditCidadeIn")
		self.gridLayout.addWidget(self.lineEditCidadeIn, 2, 0, 1, 1)
		self.labelCadastrar = QtWidgets.QLabel(self.frame)
		self.labelCadastrar.setEnabled(True)
		self.labelCadastrar.setMinimumSize(QtCore.QSize(0, 40))
		self.labelCadastrar.setMaximumSize(QtCore.QSize(16777215, 40))
		font = QtGui.QFont()
		font.setPointSize(12)
		font.setBold(True)
		font.setWeight(75)
		self.labelCadastrar.setFont(font)
		self.labelCadastrar.setStyleSheet("QLabel {\n"
"    color: rgb(255, 255, 255);\n"
"}")
		self.labelCadastrar.setAlignment(QtCore.Qt.AlignCenter)
		self.labelCadastrar.setObjectName("labelCadastrar")
		self.gridLayout.addWidget(self.labelCadastrar, 0, 0, 1, 1)
		self.labelBuscar = QtWidgets.QLabel(self.frame)
		self.labelBuscar.setEnabled(True)
		self.labelBuscar.setMinimumSize(QtCore.QSize(0, 40))
		self.labelBuscar.setMaximumSize(QtCore.QSize(16777215, 40))
		font = QtGui.QFont()
		font.setPointSize(12)
		font.setBold(True)
		font.setWeight(75)
		self.labelBuscar.setFont(font)
		self.labelBuscar.setStyleSheet("QLabel {\n"
"    color: rgb(255, 255, 255);\n"
"}")
		self.labelBuscar.setAlignment(QtCore.Qt.AlignCenter)
		self.labelBuscar.setObjectName("labelBuscar")
		self.gridLayout.addWidget(self.labelBuscar, 8, 0, 1, 1)
		self.lineEditCidadeOut = QtWidgets.QLineEdit(self.frame)
		self.lineEditCidadeOut.setEnabled(False)
		sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
		sizePolicy.setHorizontalStretch(0)
		sizePolicy.setVerticalStretch(0)
		sizePolicy.setHeightForWidth(self.lineEditCidadeOut.sizePolicy().hasHeightForWidth())
		self.lineEditCidadeOut.setSizePolicy(sizePolicy)
		self.lineEditCidadeOut.setMinimumSize(QtCore.QSize(550, 40))
		self.lineEditCidadeOut.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
		self.lineEditCidadeOut.setStyleSheet("QLineEdit {\n"
"    border: 2px solid rgb(45, 45, 45);\n"
"    border-radius: 5px;\n"
"    padding: 10px;\n"
"    background-color: rgb(30, 30, 30);\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"QLineEdit:hover {\n"
"    border: 2px solid rgb(55, 55, 55);\n"
"}\n"
"\n"
"QLineEdit:focus {\n"
"    border: 2px solid rgb(53, 97, 255);\n"
"}")
		self.lineEditCidadeOut.setMaxLength(60)
		self.lineEditCidadeOut.setObjectName("lineEditCidadeOut")
		self.gridLayout.addWidget(self.lineEditCidadeOut, 14, 0, 1, 1)
		self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
		self.horizontalLayout_2.setObjectName("horizontalLayout_2")
		self.pushButtonCadastrar = QtWidgets.QPushButton(self.frame)
		self.pushButtonCadastrar.setMinimumSize(QtCore.QSize(100, 40))
		self.pushButtonCadastrar.setMaximumSize(QtCore.QSize(100, 40))
		font = QtGui.QFont()
		font.setFamily("Unispace")
		font.setBold(True)
		font.setWeight(75)
		self.pushButtonCadastrar.setFont(font)
		self.pushButtonCadastrar.setStyleSheet("QPushButton {\n"
"    \n"
"    background-color: rgb(94, 53, 177);\n"
"    border: 2px solid rgb(81, 45, 168);\n"
"    border-radius: 5px;\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    \n"
"    background-color: rgb(60, 60, 60);\n"
"    border: 2px solid rgb(70,70,70);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    \n"
"    background-color: rgb(40, 40, 40);\n"
"    border: 2px solid rgb(81, 45, 168);\n"
"    color: rgb(255, 255, 255);\n"
"}")
		self.pushButtonCadastrar.setObjectName("pushButtonCadastrar")
		self.horizontalLayout_2.addWidget(self.pushButtonCadastrar)
		self.gridLayout.addLayout(self.horizontalLayout_2, 5, 0, 1, 1)
		self.verticalLayout_2.addWidget(self.frame)
		MainWindow.setCentralWidget(self.centralwidget)

		self.retranslateUi(MainWindow)
		QtCore.QMetaObject.connectSlotsByName(MainWindow)

	def retranslateUi(self, MainWindow):
		_translate = QtCore.QCoreApplication.translate
		MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
		self.lineEditCpfIn.setPlaceholderText(_translate("MainWindow", "CPF"))
		self.lineEditNascimentoIn.setPlaceholderText(_translate("MainWindow", "DATA DE NASCIMENTO"))
		self.lineEditCpfBusca.setPlaceholderText(_translate("MainWindow", "CPF"))
		self.pushButtonBuscar.setText(_translate("MainWindow", "Buscar"))
		self.lineEditNomeIn.setPlaceholderText(_translate("MainWindow", "NOME"))
		self.lineEditNascimentoOut.setPlaceholderText(_translate("MainWindow", "DATA DE NASCIMENTO"))
		self.lineEditNomeOut.setPlaceholderText(_translate("MainWindow", "NOME"))
		self.lineEditCidadeIn.setPlaceholderText(_translate("MainWindow", "CIDADE"))
		self.labelCadastrar.setText(_translate("MainWindow", "Cadastrar"))
		self.labelBuscar.setText(_translate("MainWindow", "Buscar"))
		self.lineEditCidadeOut.setPlaceholderText(_translate("MainWindow", "CIDADE"))
		self.pushButtonCadastrar.setText(_translate("MainWindow", "Cadastrar"))


# if __name__ == "__main__":
# 	import sys
# 	app = QtWidgets.QApplication(sys.argv)
# 	MainWindow = QtWidgets.QMainWindow()
# 	ui = Ui_MainWindow()
# 	ui.setupUi(MainWindow)
# 	MainWindow.show()
# 	sys.exit(app.exec_())
