# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\ui_mainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
	def setupUi(self, MainWindow):
		MainWindow.setObjectName("MainWindow")
		MainWindow.resize(769, 595)
		MainWindow.setStyleSheet("QFrame {\n"
"    color: rgb(40, 40, 40)\n"
"}")
		self.centralwidget = QtWidgets.QWidget(MainWindow)
		self.centralwidget.setObjectName("centralwidget")
		self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
		self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
		self.verticalLayout_2.setSpacing(0)
		self.verticalLayout_2.setObjectName("verticalLayout_2")
		self.frame = QtWidgets.QFrame(self.centralwidget)
		self.frame.setStyleSheet("background-color: rgb(40, 40, 40);")
		self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
		self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
		self.frame.setObjectName("frame")
		self.gridLayout = QtWidgets.QGridLayout(self.frame)
		self.gridLayout.setObjectName("gridLayout")
		spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
		self.gridLayout.addItem(spacerItem, 1, 2, 1, 1)
		self.labelBuscar = QtWidgets.QLabel(self.frame)
		self.labelBuscar.setEnabled(True)
		self.labelBuscar.setMinimumSize(QtCore.QSize(0, 40))
		self.labelBuscar.setMaximumSize(QtCore.QSize(16777215, 40))
		font = QtGui.QFont()
		font.setPointSize(12)
		font.setBold(True)
		font.setWeight(75)
		self.labelBuscar.setFont(font)
		self.labelBuscar.setStyleSheet("QLabel {color: rgb(255, 255, 255);}")
		self.labelBuscar.setAlignment(QtCore.Qt.AlignCenter)
		self.labelBuscar.setObjectName("labelBuscar")
		self.gridLayout.addWidget(self.labelBuscar, 0, 2, 1, 1)
		self.pushButtonScreenRegister = QtWidgets.QPushButton(self.frame)
		self.pushButtonScreenRegister.setMinimumSize(QtCore.QSize(100, 30))
		self.pushButtonScreenRegister.setMaximumSize(QtCore.QSize(100, 40))
		font = QtGui.QFont()
		font.setFamily("Unispace")
		font.setBold(True)
		font.setWeight(75)
		self.pushButtonScreenRegister.setFont(font)
		self.pushButtonScreenRegister.setStyleSheet("QPushButton {background-color: rgb(94, 53, 177);border: 2px solid rgb(81, 45, 168);border-radius: 5px;color: rgb(255, 255, 255);}\n"
"QPushButton:hover {background-color: rgb(60, 60, 60);border: 2px solid rgb(70,70,70);}\n"
"QPushButton:pressed {background-color: rgb(40, 40, 40);border: 2px solid rgb(81, 45, 168);color: rgb(255, 255, 255);}")
		self.pushButtonScreenRegister.setObjectName("pushButtonScreenRegister")
		self.gridLayout.addWidget(self.pushButtonScreenRegister, 1, 1, 1, 1)
		spacerItem1 = QtWidgets.QSpacerItem(100, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
		self.gridLayout.addItem(spacerItem1, 1, 4, 1, 1)
		spacerItem2 = QtWidgets.QSpacerItem(100, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
		self.gridLayout.addItem(spacerItem2, 1, 0, 1, 1)
		self.pushButtonScreenSearch = QtWidgets.QPushButton(self.frame)
		self.pushButtonScreenSearch.setMinimumSize(QtCore.QSize(100, 30))
		self.pushButtonScreenSearch.setMaximumSize(QtCore.QSize(100, 40))
		font = QtGui.QFont()
		font.setFamily("Unispace")
		font.setBold(True)
		font.setWeight(75)
		self.pushButtonScreenSearch.setFont(font)
		self.pushButtonScreenSearch.setStyleSheet("QPushButton {background-color: rgb(94, 53, 177);border: 2px solid rgb(81, 45, 168);border-radius: 5px;color: rgb(255, 255, 255);}\n"
"QPushButton:hover {background-color: rgb(60, 60, 60);border: 2px solid rgb(70,70,70);}\n"
"QPushButton:pressed {background-color: rgb(40, 40, 40);border: 2px solid rgb(81, 45, 168);color: rgb(255, 255, 255);}")
		self.pushButtonScreenSearch.setObjectName("pushButtonScreenSearch")
		self.gridLayout.addWidget(self.pushButtonScreenSearch, 1, 3, 1, 1)
		self.verticalLayout_2.addWidget(self.frame)
		MainWindow.setCentralWidget(self.centralwidget)

		self.retranslateUi(MainWindow)
		QtCore.QMetaObject.connectSlotsByName(MainWindow)

	def retranslateUi(self, MainWindow):
		_translate = QtCore.QCoreApplication.translate
		MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
		self.labelBuscar.setText(_translate("MainWindow", "Controle de Pessoas"))
		self.pushButtonScreenRegister.setText(_translate("MainWindow", "Cadastrar"))
		self.pushButtonScreenSearch.setText(_translate("MainWindow", "Buscar"))


if __name__ == "__main__":
	import sys
	app = QtWidgets.QApplication(sys.argv)
	MainWindow = QtWidgets.QMainWindow()
	ui = Ui_MainWindow()
	ui.setupUi(MainWindow)
	MainWindow.show()
	sys.exit(app.exec_())
