# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\ui_registerWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_RegisterWindow(object):
    def setupUi(self, RegisterWindow):
        RegisterWindow.setObjectName("RegisterWindow")
        RegisterWindow.resize(769, 595)
        RegisterWindow.setStyleSheet("QFrame {\n"
"    color: rgb(40, 40, 40)\n"
"}")
        self.centralwidget = QtWidgets.QWidget(RegisterWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setStyleSheet("background-color: rgb(40, 40, 40);")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout = QtWidgets.QGridLayout(self.frame)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.pushButtonRegister = QtWidgets.QPushButton(self.frame)
        self.pushButtonRegister.setMinimumSize(QtCore.QSize(100, 40))
        self.pushButtonRegister.setMaximumSize(QtCore.QSize(100, 40))
        font = QtGui.QFont()
        font.setFamily("Unispace")
        font.setBold(True)
        font.setWeight(75)
        self.pushButtonRegister.setFont(font)
        self.pushButtonRegister.setStyleSheet("QPushButton {background-color: rgb(94, 53, 177);border: 2px solid rgb(81, 45, 168);border-radius: 5px;color: rgb(255, 255, 255);}\n"
"QPushButton:hover {background-color: rgb(60, 60, 60);border: 2px solid rgb(70,70,70);}\n"
"QPushButton:pressed {background-color: rgb(40, 40, 40);border: 2px solid rgb(81, 45, 168);color: rgb(255, 255, 255);}")
        self.pushButtonRegister.setObjectName("pushButtonRegister")
        self.horizontalLayout_2.addWidget(self.pushButtonRegister)
        self.gridLayout.addLayout(self.horizontalLayout_2, 5, 0, 1, 1)
        self.lineEditCpfIn = QtWidgets.QLineEdit(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEditCpfIn.sizePolicy().hasHeightForWidth())
        self.lineEditCpfIn.setSizePolicy(sizePolicy)
        self.lineEditCpfIn.setMinimumSize(QtCore.QSize(550, 40))
        self.lineEditCpfIn.setTabletTracking(True)
        self.lineEditCpfIn.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.lineEditCpfIn.setStyleSheet("QLineEdit {border: 2px solid rgb(45, 45, 45);border-radius: 5px;padding: 10px;background-color: rgb(30, 30, 30);color: rgb(255, 255, 255);}\n"
"QLineEdit:hover {border: 2px solid rgb(55, 55, 55);}\n"
"QLineEdit:focus {border: 2px solid rgb(94, 53, 177);}")
        self.lineEditCpfIn.setMaxLength(60)
        self.lineEditCpfIn.setObjectName("lineEditCpfIn")
        self.gridLayout.addWidget(self.lineEditCpfIn, 3, 0, 1, 1)
        self.lineEditDateIn = QtWidgets.QLineEdit(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEditDateIn.sizePolicy().hasHeightForWidth())
        self.lineEditDateIn.setSizePolicy(sizePolicy)
        self.lineEditDateIn.setMinimumSize(QtCore.QSize(550, 40))
        self.lineEditDateIn.setTabletTracking(True)
        self.lineEditDateIn.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.lineEditDateIn.setStyleSheet("QLineEdit {border: 2px solid rgb(45, 45, 45);border-radius: 5px;padding: 10px;background-color: rgb(30, 30, 30);color: rgb(255, 255, 255);}\n"
"QLineEdit:hover {border: 2px solid rgb(55, 55, 55);}\n"
"QLineEdit:focus {border: 2px solid rgb(94, 53, 177);}")
        self.lineEditDateIn.setMaxLength(60)
        self.lineEditDateIn.setObjectName("lineEditDateIn")
        self.gridLayout.addWidget(self.lineEditDateIn, 4, 0, 1, 1)
        self.lineEditCityIn = QtWidgets.QLineEdit(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEditCityIn.sizePolicy().hasHeightForWidth())
        self.lineEditCityIn.setSizePolicy(sizePolicy)
        self.lineEditCityIn.setMinimumSize(QtCore.QSize(550, 40))
        self.lineEditCityIn.setTabletTracking(True)
        self.lineEditCityIn.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.lineEditCityIn.setStyleSheet("QLineEdit {border: 2px solid rgb(45, 45, 45);border-radius: 5px;padding: 10px;background-color: rgb(30, 30, 30);color: rgb(255, 255, 255);}\n"
"QLineEdit:hover {border: 2px solid rgb(55, 55, 55);}\n"
"QLineEdit:focus {border: 2px solid rgb(94, 53, 177);}")
        self.lineEditCityIn.setMaxLength(60)
        self.lineEditCityIn.setObjectName("lineEditCityIn")
        self.gridLayout.addWidget(self.lineEditCityIn, 2, 0, 1, 1)
        self.lineEditNameIn = QtWidgets.QLineEdit(self.frame)
        self.lineEditNameIn.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEditNameIn.sizePolicy().hasHeightForWidth())
        self.lineEditNameIn.setSizePolicy(sizePolicy)
        self.lineEditNameIn.setMinimumSize(QtCore.QSize(550, 40))
        self.lineEditNameIn.setTabletTracking(True)
        self.lineEditNameIn.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.lineEditNameIn.setStyleSheet("QLineEdit {border: 2px solid rgb(45, 45, 45);border-radius: 5px;padding: 10px;background-color: rgb(30, 30, 30);color: rgb(255, 255, 255);}\n"
"QLineEdit:hover {border: 2px solid rgb(55, 55, 55);}\n"
"QLineEdit:focus {border: 2px solid rgb(94, 53, 177);}")
        self.lineEditNameIn.setMaxLength(60)
        self.lineEditNameIn.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lineEditNameIn.setObjectName("lineEditNameIn")
        self.gridLayout.addWidget(self.lineEditNameIn, 1, 0, 1, 1)
        self.labelCadastrar = QtWidgets.QLabel(self.frame)
        self.labelCadastrar.setEnabled(True)
        self.labelCadastrar.setMinimumSize(QtCore.QSize(0, 40))
        self.labelCadastrar.setMaximumSize(QtCore.QSize(16777215, 40))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.labelCadastrar.setFont(font)
        self.labelCadastrar.setStyleSheet("QLabel {color: rgb(255, 255, 255);}")
        self.labelCadastrar.setAlignment(QtCore.Qt.AlignCenter)
        self.labelCadastrar.setObjectName("labelCadastrar")
        self.gridLayout.addWidget(self.labelCadastrar, 0, 0, 1, 1)
        self.verticalLayout_2.addWidget(self.frame)
        RegisterWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(RegisterWindow)
        QtCore.QMetaObject.connectSlotsByName(RegisterWindow)

    def retranslateUi(self, RegisterWindow):
        _translate = QtCore.QCoreApplication.translate
        RegisterWindow.setWindowTitle(_translate("RegisterWindow", "MainWindow"))
        self.pushButtonRegister.setText(_translate("RegisterWindow", "Cadastrar"))
        self.lineEditCpfIn.setPlaceholderText(_translate("RegisterWindow", "CPF"))
        self.lineEditDateIn.setPlaceholderText(_translate("RegisterWindow", "DATA DE NASCIMENTO"))
        self.lineEditCityIn.setPlaceholderText(_translate("RegisterWindow", "CIDADE"))
        self.lineEditNameIn.setPlaceholderText(_translate("RegisterWindow", "NOME"))
        self.labelCadastrar.setText(_translate("RegisterWindow", "Cadastrar"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    RegisterWindow = QtWidgets.QMainWindow()
    ui = Ui_RegisterWindow()
    ui.setupUi(RegisterWindow)
    RegisterWindow.show()
    sys.exit(app.exec_())
