# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\ui_searchWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_SearchWindow(object):
	def setupUi(self, SearchWindow):
		SearchWindow.setObjectName("SearchWindow")
		SearchWindow.resize(748, 572)
		SearchWindow.setStyleSheet("QFrame {\n"
"    color: rgb(40, 40, 40)\n"
"}")
		self.centralwidget = QtWidgets.QWidget(SearchWindow)
		self.centralwidget.setObjectName("centralwidget")
		self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
		self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
		self.verticalLayout_2.setSpacing(0)
		self.verticalLayout_2.setObjectName("verticalLayout_2")
		self.frame = QtWidgets.QFrame(self.centralwidget)
		self.frame.setStyleSheet("background-color: rgb(40, 40, 40);")
		self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
		self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
		self.frame.setObjectName("frame")
		self.gridLayout = QtWidgets.QGridLayout(self.frame)
		self.gridLayout.setObjectName("gridLayout")
		self.lineEditCityOut = QtWidgets.QLineEdit(self.frame)
		self.lineEditCityOut.setEnabled(False)
		sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
		sizePolicy.setHorizontalStretch(0)
		sizePolicy.setVerticalStretch(0)
		sizePolicy.setHeightForWidth(self.lineEditCityOut.sizePolicy().hasHeightForWidth())
		self.lineEditCityOut.setSizePolicy(sizePolicy)
		self.lineEditCityOut.setMinimumSize(QtCore.QSize(550, 40))
		self.lineEditCityOut.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
		self.lineEditCityOut.setStyleSheet("QLineEdit {border: 2px solid rgb(45, 45, 45);border-radius: 5px;padding: 10px;background-color: rgb(30, 30, 30);color: rgb(255, 255, 255);}\n"
"QLineEdit:hover {border: 2px solid rgb(55, 55, 55);}\n"
"QLineEdit:focus {border: 2px solid rgb(53, 97, 255);}")
		self.lineEditCityOut.setMaxLength(60)
		self.lineEditCityOut.setObjectName("lineEditCityOut")
		self.gridLayout.addWidget(self.lineEditCityOut, 8, 0, 1, 1)
		self.lineEditDateOut = QtWidgets.QLineEdit(self.frame)
		self.lineEditDateOut.setEnabled(False)
		sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
		sizePolicy.setHorizontalStretch(0)
		sizePolicy.setVerticalStretch(0)
		sizePolicy.setHeightForWidth(self.lineEditDateOut.sizePolicy().hasHeightForWidth())
		self.lineEditDateOut.setSizePolicy(sizePolicy)
		self.lineEditDateOut.setMinimumSize(QtCore.QSize(550, 40))
		self.lineEditDateOut.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
		self.lineEditDateOut.setStyleSheet("QLineEdit {border: 2px solid rgb(45, 45, 45);border-radius: 5px;padding: 10px;background-color: rgb(30, 30, 30);color: rgb(255, 255, 255);}\n"
"QLineEdit:hover {border: 2px solid rgb(55, 55, 55);}\n"
"QLineEdit:focus {border: 2px solid rgb(53, 97, 255);}")
		self.lineEditDateOut.setMaxLength(60)
		self.lineEditDateOut.setObjectName("lineEditDateOut")
		self.gridLayout.addWidget(self.lineEditDateOut, 9, 0, 1, 1)
		self.horizontalLayout = QtWidgets.QHBoxLayout()
		self.horizontalLayout.setObjectName("horizontalLayout")
		self.lineEditCpfSearch = QtWidgets.QLineEdit(self.frame)
		sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
		sizePolicy.setHorizontalStretch(0)
		sizePolicy.setVerticalStretch(0)
		sizePolicy.setHeightForWidth(self.lineEditCpfSearch.sizePolicy().hasHeightForWidth())
		self.lineEditCpfSearch.setSizePolicy(sizePolicy)
		self.lineEditCpfSearch.setMinimumSize(QtCore.QSize(300, 40))
		self.lineEditCpfSearch.setStyleSheet("QLineEdit {border: 2px solid rgb(45, 45, 45);border-radius: 5px;padding: 10px;background-color: rgb(30, 30, 30);color: rgb(255, 255, 255);}\n"
"QLineEdit:hover {border: 2px solid rgb(55, 55, 55);}\n"
"QLineEdit:focus {border: 2px solid  rgb(94, 53, 177)}")
		self.lineEditCpfSearch.setMaxLength(60)
		self.lineEditCpfSearch.setObjectName("lineEditCpfSearch")
		self.horizontalLayout.addWidget(self.lineEditCpfSearch)
		self.pushButtonSearch = QtWidgets.QPushButton(self.frame)
		self.pushButtonSearch.setMinimumSize(QtCore.QSize(100, 30))
		self.pushButtonSearch.setMaximumSize(QtCore.QSize(100, 40))
		font = QtGui.QFont()
		font.setFamily("Unispace")
		font.setBold(True)
		font.setWeight(75)
		self.pushButtonSearch.setFont(font)
		self.pushButtonSearch.setStyleSheet("QPushButton {background-color: rgb(94, 53, 177);border: 2px solid rgb(81, 45, 168);border-radius: 5px;color: rgb(255, 255, 255);}\n"
"QPushButton:hover {background-color: rgb(60, 60, 60);border: 2px solid rgb(70,70,70);}\n"
"QPushButton:pressed {background-color: rgb(40, 40, 40);border: 2px solid rgb(81, 45, 168);color: rgb(255, 255, 255);}")
		self.pushButtonSearch.setObjectName("pushButtonSearch")
		self.horizontalLayout.addWidget(self.pushButtonSearch)
		self.gridLayout.addLayout(self.horizontalLayout, 3, 0, 1, 1)
		self.labelBuscar = QtWidgets.QLabel(self.frame)
		self.labelBuscar.setEnabled(True)
		self.labelBuscar.setMinimumSize(QtCore.QSize(0, 40))
		self.labelBuscar.setMaximumSize(QtCore.QSize(16777215, 40))
		font = QtGui.QFont()
		font.setPointSize(12)
		font.setBold(True)
		font.setWeight(75)
		self.labelBuscar.setFont(font)
		self.labelBuscar.setStyleSheet("QLabel {color: rgb(255, 255, 255);}")
		self.labelBuscar.setAlignment(QtCore.Qt.AlignCenter)
		self.labelBuscar.setObjectName("labelBuscar")
		self.gridLayout.addWidget(self.labelBuscar, 2, 0, 1, 1)
		self.lineEditNameOut = QtWidgets.QLineEdit(self.frame)
		self.lineEditNameOut.setEnabled(False)
		sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
		sizePolicy.setHorizontalStretch(0)
		sizePolicy.setVerticalStretch(0)
		sizePolicy.setHeightForWidth(self.lineEditNameOut.sizePolicy().hasHeightForWidth())
		self.lineEditNameOut.setSizePolicy(sizePolicy)
		self.lineEditNameOut.setMinimumSize(QtCore.QSize(550, 40))
		self.lineEditNameOut.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
		self.lineEditNameOut.setStyleSheet("QLineEdit {border: 2px solid rgb(45, 45, 45);border-radius: 5px;padding: 10px;background-color: rgb(30, 30, 30);color: rgb(255, 255, 255);}\n"
"QLineEdit:hover {border: 2px solid rgb(55, 55, 55);}\n"
"QLineEdit:focus {border: 2px solid rgb(53, 97, 255);}")
		self.lineEditNameOut.setMaxLength(60)
		self.lineEditNameOut.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
		self.lineEditNameOut.setObjectName("lineEditNameOut")
		self.gridLayout.addWidget(self.lineEditNameOut, 7, 0, 1, 1)
		self.verticalLayout_2.addWidget(self.frame)
		SearchWindow.setCentralWidget(self.centralwidget)

		self.retranslateUi(SearchWindow)
		QtCore.QMetaObject.connectSlotsByName(SearchWindow)

	def retranslateUi(self, SearchWindow):
		_translate = QtCore.QCoreApplication.translate
		SearchWindow.setWindowTitle(_translate("SearchWindow", "MainWindow"))
		self.lineEditCityOut.setPlaceholderText(_translate("SearchWindow", "CIDADE"))
		self.lineEditDateOut.setPlaceholderText(_translate("SearchWindow", "DATA DE NASCIMENTO"))
		self.lineEditCpfSearch.setPlaceholderText(_translate("SearchWindow", "CPF"))
		self.pushButtonSearch.setText(_translate("SearchWindow", "Buscar"))
		self.labelBuscar.setText(_translate("SearchWindow", "Buscar"))
		self.lineEditNameOut.setPlaceholderText(_translate("SearchWindow", "NOME"))


if __name__ == "__main__":
	import sys
	app = QtWidgets.QApplication(sys.argv)
	SearchWindow = QtWidgets.QMainWindow()
	ui = Ui_SearchWindow()
	ui.setupUi(SearchWindow)
	SearchWindow.show()
	sys.exit(app.exec_())
